export const FETCH_DAILY_ENERGY_USAGE_REQUEST = 'FETCH_DAILY_ENERGY_USAGE_REQUEST'
export const FETCH_DAILY_ENERGY_USAGE_SUCCESS = 'FETCH_DAILY_ENERGY_USAGE_SUCCESS'
export const FETCH_DAILY_ENERGY_USAGE_FAIL = 'FETCH_DAILY_ENERGY_USAGE_FAIL'

export const FETCH_SCORE_SUMMARY_REQUEST = 'FETCH_SCORE_SUMMARY_REQUEST'
export const FETCH_SCORE_SUMMARY_SUCCESS = 'FETCH_SCORE_SUMMARY_SUCCESS'
export const FETCH_SCORE_SUMMARY_FAIL = 'FETCH_SCORE_SUMMARY_FAIL'

export const SET_ACTIVE_UI = 'SET_ACTIVE_UI'